"""add auto_targets table

Revision ID: f1a6f361aa74
Revises: e9a4d9ab1281
Create Date: 2026-07-06 19:39:02.843662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a6f361aa74'
down_revision = 'e9a4d9ab1281'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###