from __future__ import annotations

from app.services.providers.registry.model import AIModel


OPENROUTER_MODELS = [

    AIModel(
        id="openrouter-auto",
        provider="openrouter",
        model="openrouter/auto",
        category="text",
        display_name="OpenRouter Auto",
        description="Automatically routes to the best available model",
        priority=1,
        quality="ultra",
        speed="balanced",
        cost="medium",
        max_context=200000,
        supports_text=True,
        supports_vision=True,
        supports_streaming=True,
        supports_reasoning=True,
        supports_json_mode=True,
        supports_function_calling=True,
        supports_tools=True,
        fallback=(
            "openrouter-claude-sonnet-4",
            "openrouter-gpt-5.5",
            "openrouter-gemini-2.5-pro",
            "openrouter-deepseek-r1",
        ),
    ),

    AIModel(
        id="openrouter-gpt-5.5",
        provider="openrouter",
        model="openai/gpt-5.5",
        category="text",
        display_name="GPT-5.5 (OpenRouter)",
        description="GPT via OpenRouter",
        priority=2,
        quality="ultra",
        speed="high",
        cost="high",
        max_context=400000,
        supports_text=True,
        supports_reasoning=True,
        supports_streaming=True,
        supports_json_mode=True,
        supports_function_calling=True,
    ),

    AIModel(
        id="openrouter-claude-sonnet-4",
        provider="openrouter",
        model="anthropic/claude-sonnet-4",
        category="text",
        display_name="Claude Sonnet 4",
        description="Claude via OpenRouter",
        priority=3,
        quality="ultra",
        speed="high",
        cost="medium",
        max_context=200000,
        supports_text=True,
        supports_reasoning=True,
        supports_streaming=True,
        supports_json_mode=True,
        supports_function_calling=True,
    ),

    AIModel(
        id="openrouter-gemini-2.5-pro",
        provider="openrouter",
        model="google/gemini-2.5-pro",
        category="text",
        display_name="Gemini 2.5 Pro",
        description="Gemini via OpenRouter",
        priority=4,
        quality="ultra",
        speed="high",
        cost="medium",
        max_context=1000000,
        supports_text=True,
        supports_vision=True,
        supports_reasoning=True,
        supports_streaming=True,
        supports_json_mode=True,
        supports_function_calling=True,
    ),

    AIModel(
        id="openrouter-deepseek-r1",
        provider="openrouter",
        model="deepseek/deepseek-r1",
        category="reasoning",
        display_name="DeepSeek R1",
        description="DeepSeek via OpenRouter",
        priority=5,
        quality="ultra",
        speed="medium",
        cost="low",
        max_context=128000,
        supports_text=True,
        supports_reasoning=True,
        supports_streaming=True,
        supports_json_mode=True,
        supports_function_calling=True,
    ),

    AIModel(
        id="openrouter-flux",
        provider="openrouter",
        model="google/gemini-2.5-flash-image",
        category="image",
        display_name="Gemini 2.5 Flash Image (OpenRouter)",
        description="Google's Gemini image generation model via OpenRouter, a.k.a. Nano Banana",
        priority=40,
        quality="high",
        speed="high",
        cost="low",
        supports_image=True,
        max_images=1,
    ),

]